version: '3.8'
services:
    mysql_server:
        image: mysql:latest
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
            - MYSQL_DATABASE=$DB_NAME
        ports:
            - $DB_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
    api:
        depends_on:
            - mysql_server
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file: ./.env
        ports:
            - $PORT:$NODE_DOCKER_PORT
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - DB_HOST=mysql_server
            - DB_USER=$DB_USER
            - DB_PASSWORD=$DB_PASSWORD
            - DB_NAME=$DB_NAME
            - DB_PORT=$MYSQLDB_DOCKER_PORT
        stdin_open: true
        tty: true

volumes:
    db:
