import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex('suppliers').del();

    // Inserts seed entries
    await knex('suppliers').insert([
        {
            supplierId: 1,
            supplierName: 'Exotic Liquid',
            contactName: 'Charlotte Cooper',
            address: '49 Gilbert St.',
            city: 'London',
            postalCode: 'EC1 4SD',
            phone: '(171) 555-2222',
            country: 'UK',
        },
        {
            supplierId: 2,
            supplierName: 'New Orleans Cajun Delights',
            contactName: 'Shelley Burke',
            address: 'P.O. Box 78934',
            city: 'New Orleans',
            postalCode: '70117',
            phone: '(100) 555-4822',
            country: 'USA',
        },
        {
            supplierId: 3,
            supplierName: "Grandma Kelly's Homestead",
            contactName: 'Regina Murphy',
            address: '707 Oxford Rd.',
            city: 'Ann Arbor',
            postalCode: '48104',
            phone: '(313) 555-5735',
            country: 'USA',
        },
        {
            supplierId: 4,
            supplierName: 'Tokyo Traders',
            contactName: 'Yoshi Nagase',
            address: '9-8 Sekimai Musashino-shi',
            city: 'Tokyo',
            postalCode: '100',
            phone: '(03) 3555-5011',
            country: 'Japan',
        },
        {
            supplierId: 5,
            supplierName: "Cooperativa de Quesos 'Las Cabras'",
            contactName: 'Antonio del Valle Saavedra',
            address: 'Calle del Rosal 4',
            city: 'Oviedo',
            postalCode: '33007',
            phone: '(98) 598 76 54',
            country: 'Spain',
        },
        {
            supplierId: 6,
            supplierName: "Mayumi's",
            contactName: 'Mayumi Ohno',
            address: '92 Setsuko Chuo-ku',
            city: 'Osaka',
            postalCode: '545',
            phone: '(06) 431-7877',
            country: 'Japan',
        },
        {
            supplierId: 7,
            supplierName: 'Pavlova',
            contactName: ' Ltd.',
            address: 'Ian Devling',
            city: '74 Rose St. Moonie Ponds',
            postalCode: 'Melbourne',
            phone: 'Australia',
            country: '3058',
        },
        {
            supplierId: 8,
            supplierName: 'Specialty Biscuits',
            contactName: ' Ltd.',
            address: 'Peter Wilson',
            city: "29 King's Way",
            postalCode: 'Manchester',
            phone: 'UK',
            country: 'M14 GSD',
        },
        {
            supplierId: 9,
            supplierName: 'PB Knäckebröd AB',
            contactName: 'Lars Peterson',
            address: 'Kaloadagatan 13',
            city: 'Göteborg',
            postalCode: 'S-345 67',
            phone: '031-987 65 43',
            country: 'Sweden ',
        },
        {
            supplierId: 10,
            supplierName: 'Refrescos Americanas LTDA',
            contactName: 'Carlos Diaz',
            address: 'Av. das Americanas 12.890',
            city: 'São Paulo',
            postalCode: '5442',
            phone: '(11) 555 4640',
            country: 'Brazil',
        },
        {
            supplierId: 11,
            supplierName: 'Heli Süßwaren GmbH & Co. KG',
            contactName: 'Petra Winkler',
            address: 'Tiergartenstraße 5',
            city: 'Berlin',
            postalCode: '10785',
            phone: '(010) 9984510',
            country: 'Germany',
        },
        {
            supplierId: 12,
            supplierName: 'Plutzer Lebensmittelgroßmärkte AG',
            contactName: 'Martin Bein',
            address: 'Bogenallee 51',
            city: 'Frankfurt',
            postalCode: '60439',
            phone: '(069) 992755',
            country: 'Germany',
        },
        {
            supplierId: 13,
            supplierName: 'Nord-Ost-Fisch Handelsgesellschaft mbH',
            contactName: 'Sven Petersen',
            address: 'Frahmredder 112a',
            city: 'Cuxhaven',
            postalCode: '27478',
            phone: '(04721) 8713',
            country: 'Germany',
        },
        {
            supplierId: 14,
            supplierName: 'Formaggi Fortini s.r.l.',
            contactName: 'Elio Rossi',
            address: 'Viale Dante',
            city: ' 75',
            postalCode: 'Ravenna',
            phone: 'Italy',
            country: '48100',
        },
        {
            supplierId: 15,
            supplierName: 'Norske Meierier',
            contactName: 'Beate Vileid',
            address: 'Hatlevegen 5',
            city: 'Sandvika',
            postalCode: '1320',
            phone: '(0)2-953010',
            country: 'Norway',
        },
        {
            supplierId: 16,
            supplierName: 'Bigfoot Breweries',
            contactName: 'Cheryl Saylor',
            address: '3400 - 8th Avenue Suite 210',
            city: 'Bend',
            postalCode: '97101',
            phone: '(503) 555-9931',
            country: 'USA',
        },
        {
            supplierId: 17,
            supplierName: 'Svensk Sjöföda AB',
            contactName: 'Michael Björn',
            address: 'Brovallavägen 231',
            city: 'Stockholm',
            postalCode: 'S-123 45',
            phone: '08-123 45 67',
            country: 'Sweden',
        },
        {
            supplierId: 18,
            supplierName: 'Aux joyeux ecclésiastiques',
            contactName: 'Guylène Nodier',
            address: '203',
            city: ' Rue des Francs-Bourgeois',
            postalCode: 'Paris',
            phone: 'France',
            country: '75004',
        },
        {
            supplierId: 19,
            supplierName: 'New England Seafood Cannery',
            contactName: 'Robb Merchant',
            address: 'Order Processing Dept. 2100 Paul Revere Blvd.',
            city: 'Boston',
            postalCode: '02134',
            phone: '(617) 555-3267',
            country: 'USA',
        },
        {
            supplierId: 20,
            supplierName: 'Leka Trading',
            contactName: 'Chandra Leka',
            address: '471 Serangoon Loop',
            city: ' Suite #402',
            postalCode: 'Singapore',
            phone: 'Singapore',
            country: '0512',
        },
        {
            supplierId: 21,
            supplierName: 'Lyngbysild',
            contactName: 'Niels Petersen',
            address: 'Lyngbysild Fiskebakken 10',
            city: 'Lyngby',
            postalCode: '2800',
            phone: '43844108',
            country: 'Denmark',
        },
        {
            supplierId: 22,
            supplierName: 'Zaanse Snoepfabriek',
            contactName: 'Dirk Luchte',
            address: 'Verkoop Rijnweg 22',
            city: 'Zaandam',
            postalCode: '9999 ZZ',
            phone: '(12345) 1212',
            country: 'Netherlands',
        },
        {
            supplierId: 23,
            supplierName: 'Karkki Oy',
            contactName: 'Anne Heikkonen',
            address: 'Valtakatu 12',
            city: 'Lappeenranta',
            postalCode: '53120',
            phone: '(953) 10956',
            country: 'Finland',
        },
        {
            supplierId: 24,
            supplierName: "G'day",
            contactName: ' Mate',
            address: 'Wendy Mackenzie',
            city: "170 Prince Edward Parade Hunter's Hill",
            postalCode: 'Sydney',
            phone: 'Australia',
            country: '2042',
        },
        {
            supplierId: 25,
            supplierName: 'Ma Maison',
            contactName: 'Jean-Guy Lauzon',
            address: '2960 Rue St. Laurent',
            city: 'Montréal',
            postalCode: 'H1J 1C3',
            phone: '(514) 555-9022',
            country: 'Canada',
        },
        {
            supplierId: 26,
            supplierName: 'Pasta Buttini s.r.l.',
            contactName: 'Giovanni Giudici',
            address: 'Via dei Gelsomini',
            city: ' 153',
            postalCode: 'Salerno',
            phone: 'Italy',
            country: '84100',
        },
        {
            supplierId: 27,
            supplierName: 'Escargots Nouveaux',
            contactName: 'Marie Delamare',
            address: '22',
            city: ' rue H. Voiron',
            postalCode: 'Montceau',
            phone: 'France',
            country: '71300',
        },
        {
            supplierId: 28,
            supplierName: 'Gai pâturage',
            contactName: 'Eliane Noz',
            address: 'Bat. B 3',
            city: ' rue des Alpes',
            postalCode: 'Annecy',
            phone: 'France',
            country: '74000',
        },
        {
            supplierId: 29,
            supplierName: "Forêts d'érables",
            contactName: 'Chantal Goulet',
            address: '148 rue Chasseur',
            city: 'Ste-Hyacinthe',
            postalCode: 'J2S 7S8',
            phone: '(514) 555-2955',
            country: 'Canada',
        },
    ]);
}
