import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex('products').del();

    // Inserts seed entries
    await knex('products').insert([
        {
            productId: 1,
            productName: 'Chais',
            productPrice: 18,
            supplierId: 1,
            categoryId: 1,
            unit: '10 boxes x 20 bags',
        },
        {
            productId: 2,
            productName: 'Chang',
            productPrice: 19,
            supplierId: 1,
            categoryId: 1,
            unit: '24 - 12 oz bottles',
        },
        {
            productId: 3,
            productName: 'Aniseed Syrup',
            productPrice: 10,
            supplierId: 1,
            categoryId: 2,
            unit: '12 - 550 ml bottles',
        },
        {
            productId: 4,
            productName: "Chef Anton's Cajun Seasoning",
            productPrice: 22,
            supplierId: 2,
            categoryId: 2,
            unit: '48 - 6 oz jars',
        },
        {
            productId: 5,
            productName: "Chef Anton's Gumbo Mix",
            productPrice: 21,
            supplierId: 2,
            categoryId: 2,
            unit: '36 boxes',
        },
        {
            productId: 6,
            productName: "Grandma's Boysenberry Spread",
            productPrice: 25,
            supplierId: 3,
            categoryId: 2,
            unit: '12 - 8 oz jars',
        },
        {
            productId: 7,
            productName: "Uncle Bob's Organic Dried Pears",
            productPrice: 30,
            supplierId: 3,
            categoryId: 7,
            unit: '12 - 1 lb pkgs.',
        },
        {
            productId: 8,
            productName: 'Northwoods Cranberry Sauce',
            productPrice: 40,
            supplierId: 3,
            categoryId: 2,
            unit: '12 - 12 oz jars',
        },
        {
            productId: 9,
            productName: 'Mishi Kobe Niku',
            productPrice: 97,
            supplierId: 4,
            categoryId: 6,
            unit: '18 - 500 g pkgs.',
        },
        {
            productId: 10,
            productName: 'Ikura',
            productPrice: 31,
            supplierId: 4,
            categoryId: 8,
            unit: '12 - 200 ml jars',
        },
        {
            productId: 11,
            productName: 'Queso Cabrales',
            productPrice: 21,
            supplierId: 5,
            categoryId: 4,
            unit: '1 kg pkg.',
        },
        {
            productId: 12,
            productName: 'Queso Manchego La Pastora',
            productPrice: 38,
            supplierId: 5,
            categoryId: 4,
            unit: '10 - 500 g pkgs.',
        },
        {
            productId: 13,
            productName: 'Konbu',
            productPrice: 6,
            supplierId: 6,
            categoryId: 8,
            unit: '2 kg box',
        },
        {
            productId: 14,
            productName: 'Tofu',
            productPrice: 23,
            supplierId: 6,
            categoryId: 7,
            unit: '40 - 100 g pkgs.',
        },
        {
            productId: 15,
            productName: 'Genen Shouyu',
            productPrice: 16,
            supplierId: 6,
            categoryId: 2,
            unit: '24 - 250 ml bottles',
        },
        {
            productId: 16,
            productName: 'Pavlova',
            productPrice: 17,
            supplierId: 7,
            categoryId: 3,
            unit: '32 - 500 g boxes',
        },
        {
            productId: 17,
            productName: 'Alice Mutton',
            productPrice: 39,
            supplierId: 7,
            categoryId: 6,
            unit: '20 - 1 kg tins',
        },
        {
            productId: 18,
            productName: 'Carnarvon Tigers',
            productPrice: 63,
            supplierId: 7,
            categoryId: 8,
            unit: '16 kg pkg.',
        },
        {
            productId: 19,
            productName: 'Teatime Chocolate Biscuits',
            productPrice: 9,
            supplierId: 8,
            categoryId: 3,
            unit: '10 boxes x 12 pieces',
        },
        {
            productId: 20,
            productName: "Sir Rodney's Marmalade",
            productPrice: 81,
            supplierId: 8,
            categoryId: 3,
            unit: '30 gift boxes',
        },
        {
            productId: 21,
            productName: "Sir Rodney's Scones",
            productPrice: 10,
            supplierId: 8,
            categoryId: 3,
            unit: '24 pkgs. x 4 pieces',
        },
        {
            productId: 22,
            productName: "Gustaf's Knäckebröd",
            productPrice: 21,
            supplierId: 9,
            categoryId: 5,
            unit: '24 - 500 g pkgs.',
        },
        {
            productId: 23,
            productName: 'Tunnbröd',
            productPrice: 9,
            supplierId: 9,
            categoryId: 5,
            unit: '12 - 250 g pkgs.',
        },
        {
            productId: 24,
            productName: 'Guaraná Fantástica',
            productPrice: 5,
            supplierId: 10,
            categoryId: 1,
            unit: '12 - 355 ml cans',
        },
        {
            productId: 25,
            productName: 'NuNuCa Nuß-Nougat-Creme',
            productPrice: 14,
            supplierId: 11,
            categoryId: 3,
            unit: '20 - 450 g glasses',
        },
        {
            productId: 26,
            productName: 'Gumbär Gummibärchen',
            productPrice: 31,
            supplierId: 11,
            categoryId: 3,
            unit: '100 - 250 g bags',
        },
        {
            productId: 27,
            productName: 'Schoggi Schokolade',
            productPrice: 44,
            supplierId: 11,
            categoryId: 3,
            unit: '100 - 100 g pieces',
        },
        {
            productId: 28,
            productName: 'Rössle Sauerkraut',
            productPrice: 46,
            supplierId: 12,
            categoryId: 7,
            unit: '25 - 825 g cans',
        },
        {
            productId: 29,
            productName: 'Thüringer Rostbratwurst',
            productPrice: 124,
            supplierId: 12,
            categoryId: 6,
            unit: '50 bags x 30 sausgs.',
        },
        {
            productId: 30,
            productName: 'Nord-Ost Matjeshering',
            productPrice: 26,
            supplierId: 13,
            categoryId: 8,
            unit: '10 - 200 g glasses',
        },
        {
            productId: 31,
            productName: 'Gorgonzola Telino',
            productPrice: 13,
            supplierId: 14,
            categoryId: 4,
            unit: '12 - 100 g pkgs',
        },
        {
            productId: 32,
            productName: 'Mascarpone Fabioli',
            productPrice: 32,
            supplierId: 14,
            categoryId: 4,
            unit: '24 - 200 g pkgs.',
        },
        {
            productId: 33,
            productName: 'Geitost',
            productPrice: 3,
            supplierId: 15,
            categoryId: 4,
            unit: '500 g',
        },
        {
            productId: 34,
            productName: 'Sasquatch Ale',
            productPrice: 14,
            supplierId: 16,
            categoryId: 1,
            unit: '24 - 12 oz bottles',
        },
        {
            productId: 35,
            productName: 'Steeleye Stout',
            productPrice: 18,
            supplierId: 16,
            categoryId: 1,
            unit: '24 - 12 oz bottles',
        },
        {
            productId: 36,
            productName: 'Inlagd Sill',
            productPrice: 19,
            supplierId: 17,
            categoryId: 8,
            unit: '24 - 250 g jars',
        },
        {
            productId: 37,
            productName: 'Gravad lax',
            productPrice: 26,
            supplierId: 17,
            categoryId: 8,
            unit: '12 - 500 g pkgs.',
        },
        {
            productId: 38,
            productName: 'Côte de Blaye',
            productPrice: 264,
            supplierId: 18,
            categoryId: 1,
            unit: '12 - 75 cl bottles',
        },
        {
            productId: 39,
            productName: 'Chartreuse verte',
            productPrice: 18,
            supplierId: 18,
            categoryId: 1,
            unit: '750 cc per bottle',
        },
        {
            productId: 40,
            productName: 'Boston Crab Meat',
            productPrice: 18,
            supplierId: 19,
            categoryId: 8,
            unit: '24 - 4 oz tins',
        },
        {
            productId: 41,
            productName: "Jack's New England Clam Chowder",
            productPrice: 10,
            supplierId: 19,
            categoryId: 8,
            unit: '12 - 12 oz cans',
        },
        {
            productId: 42,
            productName: 'Singaporean Hokkien Fried Mee',
            productPrice: 14,
            supplierId: 20,
            categoryId: 5,
            unit: '32 - 1 kg pkgs.',
        },
        {
            productId: 43,
            productName: 'Ipoh Coffee',
            productPrice: 46,
            supplierId: 20,
            categoryId: 1,
            unit: '16 - 500 g tins',
        },
        {
            productId: 44,
            productName: 'Gula Malacca',
            productPrice: 19,
            supplierId: 20,
            categoryId: 2,
            unit: '20 - 2 kg bags',
        },
        {
            productId: 45,
            productName: 'Røgede sild',
            productPrice: 10,
            supplierId: 21,
            categoryId: 8,
            unit: '1k pkg.',
        },
        {
            productId: 46,
            productName: 'Spegesild',
            productPrice: 12,
            supplierId: 21,
            categoryId: 8,
            unit: '4 - 450 g glasses',
        },
        {
            productId: 47,
            productName: 'Zaanse koeken',
            productPrice: 10,
            supplierId: 22,
            categoryId: 3,
            unit: '10 - 4 oz boxes',
        },
        {
            productId: 48,
            productName: 'Chocolade',
            productPrice: 13,
            supplierId: 22,
            categoryId: 3,
            unit: '10 pkgs.',
        },
        {
            productId: 49,
            productName: 'Maxilaku',
            productPrice: 20,
            supplierId: 23,
            categoryId: 3,
            unit: '24 - 50 g pkgs.',
        },
        {
            productId: 50,
            productName: 'Valkoinen suklaa',
            productPrice: 16,
            supplierId: 23,
            categoryId: 3,
            unit: '12 - 100 g bars',
        },
        {
            productId: 51,
            productName: 'Manjimup Dried Apples',
            productPrice: 53,
            supplierId: 24,
            categoryId: 7,
            unit: '50 - 300 g pkgs.',
        },
        {
            productId: 52,
            productName: 'Filo Mix',
            productPrice: 7,
            supplierId: 24,
            categoryId: 5,
            unit: '16 - 2 kg boxes',
        },
        {
            productId: 53,
            productName: 'Perth Pasties',
            productPrice: 33,
            supplierId: 24,
            categoryId: 6,
            unit: '48 pieces',
        },
        {
            productId: 54,
            productName: 'Tourtière',
            productPrice: 7,
            supplierId: 25,
            categoryId: 6,
            unit: '16 pies',
        },
        {
            productId: 55,
            productName: 'Pâté chinois',
            productPrice: 24,
            supplierId: 25,
            categoryId: 6,
            unit: '24 boxes x 2 pies',
        },
        {
            productId: 56,
            productName: 'Gnocchi di nonna Alice',
            productPrice: 38,
            supplierId: 26,
            categoryId: 5,
            unit: '24 - 250 g pkgs.',
        },
        {
            productId: 57,
            productName: 'Ravioli Angelo',
            productPrice: 20,
            supplierId: 26,
            categoryId: 5,
            unit: '24 - 250 g pkgs.',
        },
        {
            productId: 58,
            productName: 'Escargots de Bourgogne',
            productPrice: 13,
            supplierId: 27,
            categoryId: 8,
            unit: '24 pieces',
        },
        {
            productId: 59,
            productName: 'Raclette Courdavault',
            productPrice: 55,
            supplierId: 28,
            categoryId: 4,
            unit: '5 kg pkg.',
        },
        {
            productId: 60,
            productName: 'Camembert Pierrot',
            productPrice: 34,
            supplierId: 28,
            categoryId: 4,
            unit: '15 - 300 g rounds',
        },
        {
            productId: 61,
            productName: "Sirop d'érable",
            productPrice: 29,
            supplierId: 29,
            categoryId: 2,
            unit: '24 - 500 ml bottles',
        },
        {
            productId: 62,
            productName: 'Tarte au sucre',
            productPrice: 49,
            supplierId: 29,
            categoryId: 3,
            unit: '48 pies',
        },
        {
            productId: 63,
            productName: 'Vegie-spread',
            productPrice: 44,
            supplierId: 7,
            categoryId: 2,
            unit: '15 - 625 g jars',
        },
        {
            productId: 64,
            productName: 'Wimmers gute Semmelknödel',
            productPrice: 33,
            supplierId: 12,
            categoryId: 5,
            unit: '20 bags x 4 pieces',
        },
        {
            productId: 65,
            productName: 'Louisiana Fiery Hot Pepper Sauce',
            productPrice: 21,
            supplierId: 2,
            categoryId: 2,
            unit: '32 - 8 oz bottles',
        },
        {
            productId: 66,
            productName: 'Louisiana Hot Spiced Okra',
            productPrice: 17,
            supplierId: 2,
            categoryId: 2,
            unit: '24 - 8 oz jars',
        },
        {
            productId: 67,
            productName: 'Laughing Lumberjack Lager',
            productPrice: 14,
            supplierId: 16,
            categoryId: 1,
            unit: '24 - 12 oz bottles',
        },
        {
            productId: 68,
            productName: 'Scottish Longbreads',
            productPrice: 13,
            supplierId: 8,
            categoryId: 3,
            unit: '10 boxes x 8 pieces',
        },
        {
            productId: 69,
            productName: 'Gudbrandsdalsost',
            productPrice: 36,
            supplierId: 15,
            categoryId: 4,
            unit: '10 kg pkg.',
        },
        {
            productId: 70,
            productName: 'Outback Lager',
            productPrice: 15,
            supplierId: 7,
            categoryId: 1,
            unit: '24 - 355 ml bottles',
        },
        {
            productId: 71,
            productName: 'Fløtemysost',
            productPrice: 22,
            supplierId: 15,
            categoryId: 4,
            unit: '10 - 500 g pkgs.',
        },
        {
            productId: 72,
            productName: 'Mozzarella di Giovanni',
            productPrice: 35,
            supplierId: 14,
            categoryId: 4,
            unit: '24 - 200 g pkgs.',
        },
        {
            productId: 73,
            productName: 'Röd Kaviar',
            productPrice: 15,
            supplierId: 17,
            categoryId: 8,
            unit: '24 - 150 g jars',
        },
        {
            productId: 74,
            productName: 'Longlife Tofu',
            productPrice: 10,
            supplierId: 4,
            categoryId: 7,
            unit: '5 kg pkg.',
        },
        {
            productId: 75,
            productName: 'Rhönbräu Klosterbier',
            productPrice: 8,
            supplierId: 12,
            categoryId: 1,
            unit: '24 - 0.5 l bottles',
        },
        {
            productId: 76,
            productName: 'Lakkalikööri',
            productPrice: 18,
            supplierId: 23,
            categoryId: 1,
            unit: '500 ml ',
        },
        {
            productId: 77,
            productName: 'Original Frankfurter grüne Soße',
            productPrice: 13,
            supplierId: 12,
            categoryId: 2,
            unit: '12 boxes',
        },
    ]);
}
