import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex('customers').del();

    // Inserts seed entries
    await knex('customers').insert([
        {
            customerId: 1,
            customerName: 'Alfreds Futterkiste',
            customerPhone: '191700380001',
            customerEmail: 'alfreds.futterkiste1@gmail.com',
            customerAddress: 'Obere Str. 57',
            customerCity: 'Berlin',
            customerPostalCode: '12209',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 2,
            customerName: 'Ana Trujillo Emparedados y helados',
            customerPhone: '191700380002',
            customerEmail: 'ana.trujillo.emparedados.y.helados2@gmail.com',
            customerAddress: 'Avda. de la Constitución 2222',
            customerCity: 'México D.F.',
            customerPostalCode: '05021',
            customerCountry: 'Mexico',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 3,
            customerName: 'Antonio Moreno Taquería',
            customerPhone: '191700380003',
            customerEmail: 'antonio.moreno.taquería3@gmail.com',
            customerAddress: 'Mataderos 2312',
            customerCity: 'México D.F.',
            customerPostalCode: '05023',
            customerCountry: 'Mexico',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 4,
            customerName: 'Around the Horn',
            customerPhone: '191700380004',
            customerEmail: 'around.the.horn4@gmail.com',
            customerAddress: '120 Hanover Sq.',
            customerCity: 'London',
            customerPostalCode: 'WA1 1DP',
            customerCountry: 'UK',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 5,
            customerName: 'Berglunds snabbköp',
            customerPhone: '191700380005',
            customerEmail: 'berglunds.snabbköp5@gmail.com',
            customerAddress: 'Berguvsvägen 8',
            customerCity: 'Luleå',
            customerPostalCode: 'S-958 22',
            customerCountry: 'Sweden',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 6,
            customerName: 'Blauer See Delikatessen',
            customerPhone: '191700380006',
            customerEmail: 'blauer.see.delikatessen6@gmail.com',
            customerAddress: 'Forsterstr. 57',
            customerCity: 'Mannheim',
            customerPostalCode: '68306',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 7,
            customerName: 'Blondel père et fils',
            customerPhone: '191700380007',
            customerEmail: 'blondel.père.et.fils7@gmail.com',
            customerAddress: '24',
            customerCity: ' place Kléber',
            customerPostalCode: 'Strasbourg',
            customerCountry: '67000',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 8,
            customerName: 'Bólido Comidas preparadas',
            customerPhone: '191700380008',
            customerEmail: 'bólido.comidas.preparadas8@gmail.com',
            customerAddress: 'C/ Araquil',
            customerCity: ' 67',
            customerPostalCode: 'Madrid',
            customerCountry: '28023',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 9,
            customerName: "Bon app'",
            customerPhone: '191700380009',
            customerEmail: "bon.app'9@gmail.com",
            customerAddress: '12',
            customerCity: ' rue des Bouchers',
            customerPostalCode: 'Marseille',
            customerCountry: '13008',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 10,
            customerName: 'Bottom-Dollar Marketse',
            customerPhone: '1917003800010',
            customerEmail: 'bottom-dollar.marketse10@gmail.com',
            customerAddress: '23 Tsawassen Blvd.',
            customerCity: 'Tsawassen',
            customerPostalCode: 'T2F 8M4',
            customerCountry: 'Canada',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 11,
            customerName: "B's Beverages",
            customerPhone: '1917003800011',
            customerEmail: "b's.beverages11@gmail.com",
            customerAddress: 'Fauntleroy Circus',
            customerCity: 'London',
            customerPostalCode: 'EC2 5NT',
            customerCountry: 'UK',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 12,
            customerName: 'Cactus Comidas para llevar',
            customerPhone: '1917003800012',
            customerEmail: 'cactus.comidas.para.llevar12@gmail.com',
            customerAddress: 'Cerrito 333',
            customerCity: 'Buenos Aires',
            customerPostalCode: '1010',
            customerCountry: 'Argentina',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 13,
            customerName: 'Centro comercial Moctezuma',
            customerPhone: '1917003800013',
            customerEmail: 'centro.comercial.moctezuma13@gmail.com',
            customerAddress: 'Sierras de Granada 9993',
            customerCity: 'México D.F.',
            customerPostalCode: '05022',
            customerCountry: 'Mexico',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 14,
            customerName: 'Chop-suey Chinese',
            customerPhone: '1917003800014',
            customerEmail: 'chop-suey.chinese14@gmail.com',
            customerAddress: 'Hauptstr. 29',
            customerCity: 'Bern',
            customerPostalCode: '3012',
            customerCountry: 'Switzerland',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 15,
            customerName: 'Comércio Mineiro',
            customerPhone: '1917003800015',
            customerEmail: 'comércio.mineiro15@gmail.com',
            customerAddress: 'Av. dos Lusíadas',
            customerCity: ' 23',
            customerPostalCode: 'São Paulo',
            customerCountry: '05432-043',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 16,
            customerName: 'Consolidated Holdings',
            customerPhone: '1917003800016',
            customerEmail: 'consolidated.holdings16@gmail.com',
            customerAddress: 'Berkeley Gardens 12 Brewery ',
            customerCity: 'London',
            customerPostalCode: 'WX1 6LT',
            customerCountry: 'UK',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 17,
            customerName: 'Drachenblut Delikatessend',
            customerPhone: '1917003800017',
            customerEmail: 'drachenblut.delikatessend17@gmail.com',
            customerAddress: 'Walserweg 21',
            customerCity: 'Aachen',
            customerPostalCode: '52066',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 18,
            customerName: 'Du monde entier',
            customerPhone: '1917003800018',
            customerEmail: 'du.monde.entier18@gmail.com',
            customerAddress: '67',
            customerCity: ' rue des Cinquante Otages',
            customerPostalCode: 'Nantes',
            customerCountry: '44000',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 19,
            customerName: 'Eastern Connection',
            customerPhone: '1917003800019',
            customerEmail: 'eastern.connection19@gmail.com',
            customerAddress: '35 King George',
            customerCity: 'London',
            customerPostalCode: 'WX3 6FW',
            customerCountry: 'UK',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 20,
            customerName: 'Ernst Handel',
            customerPhone: '1917003800020',
            customerEmail: 'ernst.handel20@gmail.com',
            customerAddress: 'Kirchgasse 6',
            customerCity: 'Graz',
            customerPostalCode: '8010',
            customerCountry: 'Austria',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 21,
            customerName: 'Familia Arquibaldo',
            customerPhone: '1917003800021',
            customerEmail: 'familia.arquibaldo21@gmail.com',
            customerAddress: 'Rua Orós',
            customerCity: ' 92',
            customerPostalCode: 'São Paulo',
            customerCountry: '05442-030',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 22,
            customerName: 'FISSA Fabrica Inter. Salchichas S.A.',
            customerPhone: '1917003800022',
            customerEmail: 'fissa.fabrica.inter..salchichas.s.a.22@gmail.com',
            customerAddress: 'C/ Moralzarzal',
            customerCity: ' 86',
            customerPostalCode: 'Madrid',
            customerCountry: '28034',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 23,
            customerName: 'Folies gourmandes',
            customerPhone: '1917003800023',
            customerEmail: 'folies.gourmandes23@gmail.com',
            customerAddress: '184',
            customerCity: ' chaussée de Tournai',
            customerPostalCode: 'Lille',
            customerCountry: '59000',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 24,
            customerName: 'Folk och fä HB',
            customerPhone: '1917003800024',
            customerEmail: 'folk.och.fä.hb24@gmail.com',
            customerAddress: 'Åkergatan 24',
            customerCity: 'Bräcke',
            customerPostalCode: 'S-844 67',
            customerCountry: 'Sweden',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 25,
            customerName: 'Frankenversand',
            customerPhone: '1917003800025',
            customerEmail: 'frankenversand25@gmail.com',
            customerAddress: 'Berliner Platz 43',
            customerCity: 'München',
            customerPostalCode: '80805',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 26,
            customerName: 'France restauration',
            customerPhone: '1917003800026',
            customerEmail: 'france.restauration26@gmail.com',
            customerAddress: '54',
            customerCity: ' rue Royale',
            customerPostalCode: 'Nantes',
            customerCountry: '44000',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 27,
            customerName: 'Franchi S.p.A.',
            customerPhone: '1917003800027',
            customerEmail: 'franchi.s.p.a.27@gmail.com',
            customerAddress: 'Via Monte Bianco 34',
            customerCity: 'Torino',
            customerPostalCode: '10100',
            customerCountry: 'Italy',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 28,
            customerName: 'Furia Bacalhau e Frutos do Mar',
            customerPhone: '1917003800028',
            customerEmail: 'furia.bacalhau.e.frutos.do.mar28@gmail.com',
            customerAddress: 'Jardim das rosas n. 32',
            customerCity: 'Lisboa',
            customerPostalCode: '1675',
            customerCountry: 'Portugal',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 29,
            customerName: 'Galería del gastrónomo',
            customerPhone: '1917003800029',
            customerEmail: 'galería.del.gastrónomo29@gmail.com',
            customerAddress: 'Rambla de Cataluña',
            customerCity: ' 23',
            customerPostalCode: 'Barcelona',
            customerCountry: '08022',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 30,
            customerName: 'Godos Cocina Típica',
            customerPhone: '1917003800030',
            customerEmail: 'godos.cocina.típica30@gmail.com',
            customerAddress: 'C/ Romero',
            customerCity: ' 33',
            customerPostalCode: 'Sevilla',
            customerCountry: '41101',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 31,
            customerName: 'Gourmet Lanchonetes',
            customerPhone: '1917003800031',
            customerEmail: 'gourmet.lanchonetes31@gmail.com',
            customerAddress: 'Av. Brasil',
            customerCity: ' 442',
            customerPostalCode: 'Campinas',
            customerCountry: '04876-786',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 32,
            customerName: 'Great Lakes Food Market',
            customerPhone: '1917003800032',
            customerEmail: 'great.lakes.food.market32@gmail.com',
            customerAddress: '2732 Baker Blvd.',
            customerCity: 'Eugene',
            customerPostalCode: '97403',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 33,
            customerName: 'GROSELLA-Restaurante',
            customerPhone: '1917003800033',
            customerEmail: 'grosella-restaurante33@gmail.com',
            customerAddress: '5ª Ave. Los Palos Grandes',
            customerCity: 'Caracas',
            customerPostalCode: '1081',
            customerCountry: 'Venezuela',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 34,
            customerName: 'Hanari Carnes',
            customerPhone: '1917003800034',
            customerEmail: 'hanari.carnes34@gmail.com',
            customerAddress: 'Rua do Paço',
            customerCity: ' 67',
            customerPostalCode: 'Rio de Janeiro',
            customerCountry: '05454-876',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 35,
            customerName: 'HILARIÓN-Abastos',
            customerPhone: '1917003800035',
            customerEmail: 'hilarión-abastos35@gmail.com',
            customerAddress: 'Carrera 22 con Ave. Carlos Soublette #8-35',
            customerCity: 'San Cristóbal',
            customerPostalCode: '5022',
            customerCountry: 'Venezuela',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 36,
            customerName: 'Hungry Coyote Import Store',
            customerPhone: '1917003800036',
            customerEmail: 'hungry.coyote.import.store36@gmail.com',
            customerAddress: 'customerCity Center Plaza 516 Main St.',
            customerCity: 'Elgin',
            customerPostalCode: '97827',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 37,
            customerName: 'Hungry Owl All-Night Grocers',
            customerPhone: '1917003800037',
            customerEmail: 'hungry.owl.all-night.grocers37@gmail.com',
            customerAddress: '8 Johnstown Road',
            customerCity: 'Cork',
            customerPostalCode: '',
            customerCountry: 'Ireland',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 38,
            customerName: 'Island Trading',
            customerPhone: '1917003800038',
            customerEmail: 'island.trading38@gmail.com',
            customerAddress: 'Garden House Crowther Way',
            customerCity: 'Cowes',
            customerPostalCode: 'PO31 7PJ',
            customerCountry: 'UK',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 39,
            customerName: 'Königlich Essen',
            customerPhone: '1917003800039',
            customerEmail: 'königlich.essen39@gmail.com',
            customerAddress: 'Maubelstr. 90',
            customerCity: 'Brandenburg',
            customerPostalCode: '14776',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 40,
            customerName: "La corne d'abondance",
            customerPhone: '1917003800040',
            customerEmail: "la.corne.d'abondance40@gmail.com",
            customerAddress: '67',
            customerCity: " avenue de l'Europe",
            customerPostalCode: 'Versailles',
            customerCountry: '78000',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 41,
            customerName: "La maison d'Asie",
            customerPhone: '1917003800041',
            customerEmail: "la.maison.d'asie41@gmail.com",
            customerAddress: '1 rue Alsace-Lorraine',
            customerCity: 'Toulouse',
            customerPostalCode: '31000',
            customerCountry: 'France',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 42,
            customerName: 'Laughing Bacchus Wine Cellars',
            customerPhone: '1917003800042',
            customerEmail: 'laughing.bacchus.wine.cellars42@gmail.com',
            customerAddress: '1900 Oak St.',
            customerCity: 'Vancouver',
            customerPostalCode: 'V3F 2K1',
            customerCountry: 'Canada',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 43,
            customerName: 'Lazy K Kountry Store',
            customerPhone: '1917003800043',
            customerEmail: 'lazy.k.kountry.store43@gmail.com',
            customerAddress: '12 Orchestra Terrace',
            customerCity: 'Walla Walla',
            customerPostalCode: '99362',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 44,
            customerName: 'Lehmanns Marktstand',
            customerPhone: '1917003800044',
            customerEmail: 'lehmanns.marktstand44@gmail.com',
            customerAddress: 'Magazinweg 7',
            customerCity: 'Frankfurt a.M.',
            customerPostalCode: '60528',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 45,
            customerName: "Let's Stop N Shop",
            customerPhone: '1917003800045',
            customerEmail: "let's.stop.n.shop45@gmail.com",
            customerAddress: '87 Polk St. Suite 5',
            customerCity: 'San Francisco',
            customerPostalCode: '94117',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 46,
            customerName: 'LILA-Supermercado',
            customerPhone: '1917003800046',
            customerEmail: 'lila-supermercado46@gmail.com',
            customerAddress: 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo',
            customerCity: 'Barquisimeto',
            customerPostalCode: '3508',
            customerCountry: 'Venezuela',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 47,
            customerName: 'LINO-Delicateses',
            customerPhone: '1917003800047',
            customerEmail: 'lino-delicateses47@gmail.com',
            customerAddress: 'Ave. 5 de Mayo Porlamar',
            customerCity: 'I. de Margarita',
            customerPostalCode: '4980',
            customerCountry: 'Venezuela',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 48,
            customerName: 'Lonesome Pine Restaurant',
            customerPhone: '1917003800048',
            customerEmail: 'lonesome.pine.restaurant48@gmail.com',
            customerAddress: '89 Chiaroscuro Rd.',
            customerCity: 'Portland',
            customerPostalCode: '97219',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 49,
            customerName: 'Magazzini Alimentari Riuniti',
            customerPhone: '1917003800049',
            customerEmail: 'magazzini.alimentari.riuniti49@gmail.com',
            customerAddress: 'Via Ludovico il Moro 22',
            customerCity: 'Bergamo',
            customerPostalCode: '24100',
            customerCountry: 'Italy',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 50,
            customerName: 'Maison Dewey',
            customerPhone: '1917003800050',
            customerEmail: 'maison.dewey50@gmail.com',
            customerAddress: 'Rue Joseph-Bens 532',
            customerCity: 'Bruxelles',
            customerPostalCode: 'B-1180',
            customerCountry: 'Belgium',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 51,
            customerName: 'Mère Paillarde',
            customerPhone: '1917003800051',
            customerEmail: 'mère.paillarde51@gmail.com',
            customerAddress: '43 rue St. Laurent',
            customerCity: 'Montréal',
            customerPostalCode: 'H1J 1C3',
            customerCountry: 'Canada',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 52,
            customerName: 'Morgenstern Gesundkost',
            customerPhone: '1917003800052',
            customerEmail: 'morgenstern.gesundkost52@gmail.com',
            customerAddress: 'Heerstr. 22',
            customerCity: 'Leipzig',
            customerPostalCode: '04179',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 53,
            customerName: 'North/South',
            customerPhone: '1917003800053',
            customerEmail: 'north/south53@gmail.com',
            customerAddress: 'South House 300 Queensbridge',
            customerCity: 'London',
            customerPostalCode: 'SW7 1RZ',
            customerCountry: 'UK',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 54,
            customerName: 'Océano Atlántico Ltda.',
            customerPhone: '1917003800054',
            customerEmail: 'océano.atlántico.ltda.54@gmail.com',
            customerAddress: 'Ing. Gustavo Moncada 8585 Piso 20-A',
            customerCity: 'Buenos Aires',
            customerPostalCode: '1010',
            customerCountry: 'Argentina',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 55,
            customerName: 'Old World Delicatessen',
            customerPhone: '1917003800055',
            customerEmail: 'old.world.delicatessen55@gmail.com',
            customerAddress: '2743 Bering St.',
            customerCity: 'Anchorage',
            customerPostalCode: '99508',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 56,
            customerName: 'Ottilies Käseladen',
            customerPhone: '1917003800056',
            customerEmail: 'ottilies.käseladen56@gmail.com',
            customerAddress: 'Mehrheimerstr. 369',
            customerCity: 'Köln',
            customerPostalCode: '50739',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 57,
            customerName: 'Paris spécialités',
            customerPhone: '1917003800057',
            customerEmail: 'paris.spécialités57@gmail.com',
            customerAddress: '265',
            customerCity: ' boulevard Charonne',
            customerPostalCode: 'Paris',
            customerCountry: '75012',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 58,
            customerName: 'Pericles Comidas clásicas',
            customerPhone: '1917003800058',
            customerEmail: 'pericles.comidas.clásicas58@gmail.com',
            customerAddress: 'Calle Dr. Jorge Cash 321',
            customerCity: 'México D.F.',
            customerPostalCode: '05033',
            customerCountry: 'Mexico',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 59,
            customerName: 'Piccolo und mehr',
            customerPhone: '1917003800059',
            customerEmail: 'piccolo.und.mehr59@gmail.com',
            customerAddress: 'Geislweg 14',
            customerCity: 'Salzburg',
            customerPostalCode: '5020',
            customerCountry: 'Austria',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 60,
            customerName: 'Princesa Isabel Vinhoss',
            customerPhone: '1917003800060',
            customerEmail: 'princesa.isabel.vinhoss60@gmail.com',
            customerAddress: 'Estrada da saúde n. 58',
            customerCity: 'Lisboa',
            customerPostalCode: '1756',
            customerCountry: 'Portugal',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 61,
            customerName: 'Que Delícia',
            customerPhone: '1917003800061',
            customerEmail: 'que.delícia61@gmail.com',
            customerAddress: 'Rua da Panificadora',
            customerCity: ' 12',
            customerPostalCode: 'Rio de Janeiro',
            customerCountry: '02389-673',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 62,
            customerName: 'Queen Cozinha',
            customerPhone: '1917003800062',
            customerEmail: 'queen.cozinha62@gmail.com',
            customerAddress: 'Alameda dos Canàrios',
            customerCity: ' 891',
            customerPostalCode: 'São Paulo',
            customerCountry: '05487-020',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 63,
            customerName: 'QUICK-Stop',
            customerPhone: '1917003800063',
            customerEmail: 'quick-stop63@gmail.com',
            customerAddress: 'Taucherstraße 10',
            customerCity: 'Cunewalde',
            customerPostalCode: '01307',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 64,
            customerName: 'Rancho grande',
            customerPhone: '1917003800064',
            customerEmail: 'rancho.grande64@gmail.com',
            customerAddress: 'Av. del Libertador 900',
            customerCity: 'Buenos Aires',
            customerPostalCode: '1010',
            customerCountry: 'Argentina',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 65,
            customerName: 'Rattlesnake Canyon Grocery',
            customerPhone: '1917003800065',
            customerEmail: 'rattlesnake.canyon.grocery65@gmail.com',
            customerAddress: '2817 Milton Dr.',
            customerCity: 'Albuquerque',
            customerPostalCode: '87110',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 66,
            customerName: 'Reggiani Caseifici',
            customerPhone: '1917003800066',
            customerEmail: 'reggiani.caseifici66@gmail.com',
            customerAddress: 'Strada Provinciale 124',
            customerCity: 'Reggio Emilia',
            customerPostalCode: '42100',
            customerCountry: 'Italy',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 67,
            customerName: 'Ricardo Adocicados',
            customerPhone: '1917003800067',
            customerEmail: 'ricardo.adocicados67@gmail.com',
            customerAddress: 'Av. Copacabana',
            customerCity: ' 267',
            customerPostalCode: 'Rio de Janeiro',
            customerCountry: '02389-890',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 68,
            customerName: 'Richter Supermarkt',
            customerPhone: '1917003800068',
            customerEmail: 'richter.supermarkt68@gmail.com',
            customerAddress: 'Grenzacherweg 237',
            customerCity: 'Genève',
            customerPostalCode: '1203',
            customerCountry: 'Switzerland',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 69,
            customerName: 'Romero y tomillo',
            customerPhone: '1917003800069',
            customerEmail: 'romero.y.tomillo69@gmail.com',
            customerAddress: 'Gran Vía',
            customerCity: ' 1',
            customerPostalCode: 'Madrid',
            customerCountry: '28001',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 70,
            customerName: 'Santé Gourmet',
            customerPhone: '1917003800070',
            customerEmail: 'santé.gourmet70@gmail.com',
            customerAddress: 'Erling Skakkes gate 78',
            customerCity: 'Stavern',
            customerPostalCode: '4110',
            customerCountry: 'Norway',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 71,
            customerName: 'Save-a-lot Markets',
            customerPhone: '1917003800071',
            customerEmail: 'save-a-lot.markets71@gmail.com',
            customerAddress: '187 Suffolk Ln.',
            customerCity: 'Boise',
            customerPostalCode: '83720',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 72,
            customerName: 'Seven Seas Imports',
            customerPhone: '1917003800072',
            customerEmail: 'seven.seas.imports72@gmail.com',
            customerAddress: '90 Wadhurst Rd.',
            customerCity: 'London',
            customerPostalCode: 'OX15 4NB',
            customerCountry: 'UK',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 73,
            customerName: 'Simons bistro',
            customerPhone: '1917003800073',
            customerEmail: 'simons.bistro73@gmail.com',
            customerAddress: 'Vinbæltet 34',
            customerCity: 'København',
            customerPostalCode: '1734',
            customerCountry: 'Denmark',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 74,
            customerName: 'Spécialités du monde',
            customerPhone: '1917003800074',
            customerEmail: 'spécialités.du.monde74@gmail.com',
            customerAddress: '25',
            customerCity: ' rue Lauriston',
            customerPostalCode: 'Paris',
            customerCountry: '75016',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 75,
            customerName: 'Split Rail Beer & Ale',
            customerPhone: '1917003800075',
            customerEmail: 'split.rail.beer.&.ale75@gmail.com',
            customerAddress: 'P.O. Box 555',
            customerCity: 'Lander',
            customerPostalCode: '82520',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 76,
            customerName: 'Suprêmes délices',
            customerPhone: '1917003800076',
            customerEmail: 'suprêmes.délices76@gmail.com',
            customerAddress: 'Boulevard Tirou',
            customerCity: ' 255',
            customerPostalCode: 'Charleroi',
            customerCountry: 'B-6000',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 77,
            customerName: 'The Big Cheese',
            customerPhone: '1917003800077',
            customerEmail: 'the.big.cheese77@gmail.com',
            customerAddress: '89 Jefferson Way Suite 2',
            customerCity: 'Portland',
            customerPostalCode: '97201',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 78,
            customerName: 'The Cracker Box',
            customerPhone: '1917003800078',
            customerEmail: 'the.cracker.box78@gmail.com',
            customerAddress: '55 Grizzly Peak Rd.',
            customerCity: 'Butte',
            customerPostalCode: '59801',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 79,
            customerName: 'Toms Spezialitäten',
            customerPhone: '1917003800079',
            customerEmail: 'toms.spezialitäten79@gmail.com',
            customerAddress: 'Luisenstr. 48',
            customerCity: 'Münster',
            customerPostalCode: '44087',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 80,
            customerName: 'Tortuga Restaurante',
            customerPhone: '1917003800080',
            customerEmail: 'tortuga.restaurante80@gmail.com',
            customerAddress: 'Avda. Azteca 123',
            customerCity: 'México D.F.',
            customerPostalCode: '05033',
            customerCountry: 'Mexico',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 81,
            customerName: 'Tradição Hipermercados',
            customerPhone: '1917003800081',
            customerEmail: 'tradição.hipermercados81@gmail.com',
            customerAddress: 'Av. Inês de Castro',
            customerCity: ' 414',
            customerPostalCode: 'São Paulo',
            customerCountry: '05634-030',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 82,
            customerName: "Trail's Head Gourmet Provisioners",
            customerPhone: '1917003800082',
            customerEmail: "trail's.head.gourmet.provisioners82@gmail.com",
            customerAddress: '722 DaVinci Blvd.',
            customerCity: 'Kirkland',
            customerPostalCode: '98034',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 83,
            customerName: 'Vaffeljernet',
            customerPhone: '1917003800083',
            customerEmail: 'vaffeljernet83@gmail.com',
            customerAddress: 'Smagsløget 45',
            customerCity: 'Århus',
            customerPostalCode: '8200',
            customerCountry: 'Denmark',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 84,
            customerName: 'Victuailles en stock',
            customerPhone: '1917003800084',
            customerEmail: 'victuailles.en.stock84@gmail.com',
            customerAddress: '2',
            customerCity: ' rue du Commerce',
            customerPostalCode: 'Lyon',
            customerCountry: '69004',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 85,
            customerName: 'Vins et alcools Chevalier',
            customerPhone: '1917003800085',
            customerEmail: 'vins.et.alcools.chevalier85@gmail.com',
            customerAddress: "59 rue de l'Abbaye",
            customerCity: 'Reims',
            customerPostalCode: '51100',
            customerCountry: 'France',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 86,
            customerName: 'Die Wandernde Kuh',
            customerPhone: '1917003800086',
            customerEmail: 'die.wandernde.kuh86@gmail.com',
            customerAddress: 'Adenauerallee 900',
            customerCity: 'Stuttgart',
            customerPostalCode: '70563',
            customerCountry: 'Germany',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 87,
            customerName: 'Wartian Herkku',
            customerPhone: '1917003800087',
            customerEmail: 'wartian.herkku87@gmail.com',
            customerAddress: 'Torikatu 38',
            customerCity: 'Oulu',
            customerPostalCode: '90110',
            customerCountry: 'Finland',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 88,
            customerName: 'Wellington Importadora',
            customerPhone: '1917003800088',
            customerEmail: 'wellington.importadora88@gmail.com',
            customerAddress: 'Rua do Mercado',
            customerCity: ' 12',
            customerPostalCode: 'Resende',
            customerCountry: '08737-363',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 89,
            customerName: 'White Clover Markets',
            customerPhone: '1917003800089',
            customerEmail: 'white.clover.markets89@gmail.com',
            customerAddress: '305 - 14th Ave. S. Suite 3B',
            customerCity: 'Seattle',
            customerPostalCode: '98128',
            customerCountry: 'USA',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 90,
            customerName: 'Wilman Kala',
            customerPhone: '1917003800090',
            customerEmail: 'wilman.kala90@gmail.com',
            customerAddress: 'Keskuskatu 45',
            customerCity: 'Helsinki',
            customerPostalCode: '21240',
            customerCountry: 'Finland',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 91,
            customerName: 'Wolski',
            customerPhone: '1917003800091',
            customerEmail: 'wolski91@gmail.com',
            customerAddress: 'ul. Filtrowa 68',
            customerCity: 'Walla',
            customerPostalCode: '01-012',
            customerCountry: 'Poland',
            customerPassword: '$2a$04$hnnzJ7r6p6SE5DiwG05C2.RbpLasMc/XbbZoOeLApXByoMNCiCn3C',
            isActive: 0,
        },
        {
            customerId: 98,
            customerName: 'Nazmul Haque',
            customerPhone: '1917003822',
            customerEmail: 'nazmul.haque@gmail.com',
            customerAddress: 'Obere Str. 57',
            customerCity: 'Berlin',
            customerPostalCode: '12209',
            customerCountry: 'Germany',
            customerPassword: '$2b$10$EU18kzWo9pWWz6s6AZ8B/.e7DYqnLaYksuNr.cxtFKF.s2Rq98roK',
            isActive: 0,
        },
    ]);
}
